- name: data types
  hosts: localhost
  vars:
    course: Devops with aws #string
    Tools: # list
    - Ansible
    - linux
    - shell script
    - terraform
    Experience:  #map or dictionaries
      Devops: 3  #number
      Docker: 2 
      linux: 1 
    Real_project: true #boolien
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Hi im learning {{course}}, tools covered {{Tools}} experience is {{Experience}}  real time project{{Real_project}}"