- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "this course is {{course | default ('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
    NAME: sivakumar
  tasks:
  - name: print upper case
    ansible.builtin.debug:
      msg: "{{NAME | upper}}"

- name: lower case
  hosts: localhost
  vars:
    NAME: SIVAKUMAR
  tasks:
  - name: print lower case
    ansible.builtin.debug:
      msg: "{{NAME | lower}}"

- name: minium and maximum age
  hosts: localhost
  vars:
    AGE: [12,52,6,67,89]
  tasks:
  - name: print min and max age
    ansible.builtin.debug:
      msg: minimum age is {{ AGE | min}}, maximum age is {{ AGE | max}}

- name: remove duplicates
  hosts: localhost
  vars:
  NUMBERS: [1,2,2,3,3,4,5]
  tasks:
  - name: print duplicate numbers
    ansible.builtin.debug:
      msg: dupilicates values are removed {{NUMBERS | unique}}
