- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "this course is {{course | default ('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
    NAME: sivakumar
  tasks:
  - name: print upper case
    ansible.builtin.debug:
      msg: "{{NAME | upper}}"