- name: install packages
  hosts: web
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      msg : installing packages
    name: "{{item}}"
    state: latest

    loop:
    - mysql
    - nginx
    - postfix